# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alessandro Mulé
title: Software Architect
email: ale.mule@gmail.com
website: https://rhllor.github.io/curriculum-vitae/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  rhllor
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: amule
instagram_username: rhllor86
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I've been a software developer for ages now: more or less since I was 12. It's quite a long time, isn't it? Yet I feel the need to keep improving my skills to be an even better developer.
  After thousands hours of debug and hundreds of dead and new technologies I can feel a little frustrated; but I love this job and I like to turn frustration into determination to solve any problem of any kind.
  Also, I have two supporters that help me through different stages: my dog helps me to fix code and my cat, on the other hand, help to improve tests.I love agile methodologies and constant dialogue with teams, to maximise the potential of any individual and to encourage ideas generation.
  Outside of work, I like mountain trekking, play basketball, role play and videogames.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mondora Srl SB
        link: https://www.mondora.com/
        link_text: mondora.com
        sub_title: Software Engineer / Architect
        caption: Sept 2021 - Present
        quote: >
          <mark>Java</mark> <mark>Kotlin</mark> <mark>Azure</mark> <mark>Spring</mark> <mark>Quarkus</mark> <mark>DAPR</mark> <mark>Azure</mark> <mark>Microservices Architecture</mark> <mark>JS/TS</mark> <mark>React</mark> <mark>TDD</mark> <mark>DDD</mark> <mark>Scrum</mark>
        description: | # this will include new lines to allow paragraphs
          As a Software Engineer, I work on implementing and maintaining the core service of Team Systems Digital Platform.
          The scope of my team is to implement and maintain authorization flow, shared registry and metering of usage of commercial package.
          As a Software Architect I'm working on refactoring of metering flow with focus on resource consuming. 
          In this Company, which is a flat one, I started working with International Teams as Tech Leader with Agile Methodologies.

      - layout: left
        title: Errevi System Srl
        link: https://errevi.com/
        link_text: errevi.com
        sub_title: Software Engineer
        caption: Mar 2013 - Aug 2021
        quote: >
          <mark>C#</mark> <mark>.NET Framework</mark> <mark>.NET</mark> <mark>ASP</mark> <mark>Gitlab</mark> <mark>JS/TS</mark> <mark>AngularJS</mark> <mark>TDD</mark>
        description: | # this will include new lines to allow paragraphs
          As a Software Engineer, I worked on maintaining internal tools we used to implement the company’s products.On 2016, I began the refactory of tools from the old baseline based on ASP and migrate to a new infrastructure based on AngularJS for the client interface and some rest service and windows service for the backend. 

      - layout: left
        title: Seven IT Srl
        link: https://www.ilpolodigitale.com/
        link_text: ilpolodigitale.com
        sub_title: Software Developer
        caption: July 2012 - Feb 2013
        quote: >
          <mark>C#</mark> <mark>.NET Framework</mark> <mark>MsSql</mark> <mark>PHP</mark> <mark>MySql</mark> <mark>Joomla</mark>
        description: | # this will include new lines to allow paragraphs
          As a Software Developer, I worked on developing Websites and little software application for rental cars processes.

      - layout: left
        title: Sinfo One SpA
        link: https://www.sinfo-one.com/
        link_text: sinfo-one.com
        sub_title: Analyst
        caption: Jan 2006 - June 2012
        quote: >
          <mark>Java</mark> <mark>C++</mark> <mark>Oracle</mark>
        description: | # this will include new lines to allow paragraphs
          As an Analyst, I worked on various projects for different customers. My focus was the implementation, refactoring and integration of manufacturing process with the Oracle's ERP platform E1.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ITC Bodoni
        caption: 1999 - 2004
        sub_title: Diploma on economics and software develop
        description: | # this will include new lines to allow paragraphs
          I achieved my High School Graduation Degree (Diploma Maturità) with the result of 100/100 on Economics and Information Technology (Software). 
          Main topic: Java Development. 

  - title: A Little More About Me
    layout: list # Type of content section (list/text)
    content: 
      - layout: left
        title: Basketball 
        caption: 1999 - Present
        sub_title: Bad Player and Awesome Bad Coach of senior team
        description: | # this will include new lines to allow paragraphs
          I've been playing basketball since I was 14. I'm not a skilled player but I keep playing with my friends on amateur category. We have built our own team and I’ve been the Head Coach for the last three years, now.
      
      - layout: left
        title: Role Playing 
        sub_title: Lazy DM and angry barbarian gnome
        description: | # this will include new lines to allow paragraphs
          I'm a boardgame and role's player addicted. I don't remember when i start to play but i don't stop it. 
          From 2002 to 2009 i work on play-by-chat role game base on Marvel Superhero comics. In this game multiple players can play in different multiple locations at the same moment to generate a story that evolves following their action on game. 

      - layout: left
        title: Volunteering
        sub_title: Healthcare 
        description: | # this will include new lines to allow paragraphs
          I work as a Ambassador for multiple italian non-profit organisation(AVIS, AIDO, ADMO). My focus is on blood and organ donation projects where I play as a facilitator to explain Italian Healthcare Systems issues.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
