# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alessandro Mulé
title: Software Architect
email: ale.mule@gmail.com
website: https://rhllor.github.io/curriculum-vitae/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  rhllor
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: amule
instagram_username: rhllor86
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a software developer since when i was 12, is a lot of times but i continue to improve my skill to be a better devloper. Thousands hour of debug, houndreds of dead and new technologies sometime they made me a little bit frustrated but i continue to like this Job. 
  My Dog help me to fix my code, the cat help me to improve my test. On the job i love agile methodologies and continue dialogue with team. When i'm not on the job i like mountain trekking, play basketball, role play and videogames.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mondora Srl SB
        link: https://www.mondora.com/
        link_text: mondora.com
        sub_title: Software Engineer / Architect
        caption: Sept 2021 - Present
        quote: >
          <mark>Java</mark> <mark>Kotlin</mark> <mark>Azure</mark> <mark>Spring</mark> <mark>Quarkus</mark> <mark>DAPR</mark> <mark>Azure</mark> <mark>Microservices Architecture</mark> <mark>JS/TS</mark> <mark>React</mark> <mark>TDD</mark> <mark>DDD</mark> <mark>Scrum</mark>
        description: | # this will include new lines to allow paragraphs
          As Software Engineer i work on implements and maintenance of core service of Team System's Digital Platoform. The scope of my team is implements and maintenance authorization flow, shared registry and metering of usage of commercial package. 
          As Software Architect i work on refactoring of Metering flow with focus on resource consuming. 
          In this company i started to work with international team as teach leader with agile methodologies in a flat company.

      - layout: left
        title: Errevi System Srl
        link: https://errevi.com/
        link_text: errevi.com
        sub_title: Software Engineer
        caption: Mar 2013 - Aug 2021
        quote: >
          <mark>C#</mark> <mark>.NET Framework</mark> <mark>.NET</mark> <mark>ASP</mark> <mark>Gitlab</mark> <mark>JS/TS</mark> <mark>AngularJS</mark> <mark>TDD</mark>
        description: | # this will include new lines to allow paragraphs
          As Software Engineer i worked on maintenance of internal tools that we use to implements products of company. In the 2016 i started the refactory of tools from the old baseline based on ASP and migrate to a new infrastructure based on AngularJS for the client interface and some rest service and windows service for the backend. 

      - layout: left
        title: Seven IT Srl
        link: https://www.ilpolodigitale.com/
        link_text: ilpolodigitale.com
        sub_title: Software Developer
        caption: July 2012 - Feb 2013
        quote: >
          <mark>C#</mark> <mark>.NET Framework</mark> <mark>MsSql</mark> <mark>PHP</mark> <mark>MySql</mark> <mark>Joomla</mark>
        description: | # this will include new lines to allow paragraphs
          As software developer i worked implement of Website and litte software application for rental car process.

      - layout: left
        title: Sinfo One SpA
        link: https://www.sinfo-one.com/
        link_text: sinfo-one.com
        sub_title: Analyst
        caption: Jan 2006 - June 2012
        quote: >
          <mark>Java</mark> <mark>C++</mark> <mark>Oracle</mark>
        description: | # this will include new lines to allow paragraphs
          As Analyst i worked on with different client. My focus was on implementation, refactoring and integration of manufacturing process with the Oracle's ERP platform E1.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ITC Bodoni
        caption: 1999 - 2004
        sub_title: Diploma on economics and software develop
        description: | # this will include new lines to allow paragraphs
          I archievied the Diploma on economics and software with the result of 100/100. The focus of study is on Java Development. 

  - title: A Little More About Me
    layout: list # Type of content section (list/text)
    content: 
      - layout: left
        title: Basketball 
        caption: 1999 - Present
        sub_title: Bad Player and Awesome Bad Coach of senior team
        description: | # this will include new lines to allow paragraphs
          I started to play Basketball when i was 14. I'm not a skilled player but i continue to play with my friend in amateur category. We have create own team and in the last three year i play as Head Coach.
      
      - layout: left
        title: Role Playing 
        sub_title: Lazy DM and angry barbarian gnome
        description: | # this will include new lines to allow paragraphs
          I'm a boardgame and role's player addicted. I don't remember when i start to play but i don't stop it. 
          From 2002 to 2009 i work on play-by-chat role game base on Marvel Superhero comics. In this game multiple players can play in different multiple location in the same moment to generate a story that evolving with their action on game.  

      - layout: left
        title: Volunteering
        sub_title: Healthcare 
        description: | # this will include new lines to allow paragraphs
          I work as a Ambassador for multiple italian non-profit organisation(AVIS, AIDO, ADMO). My focus is on blood and organ donation projects where i explain our problem on italian Healthcare system. 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
